### ISSUE TITLE
Unicode characters are not displayed correctly

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burst-explorer#1]
https://explorer.burstcoin.dk/?action=block_inspect&height=400518

![image](https://user-images.githubusercontent.com/5445357/53239575-f00c1f80-36ce-11e9-8acd-66525b143c52.png)

https://explorer.burstcoin.dk/?action=account&account=7936318648232813722&submenu=blocks

![image](https://user-images.githubusercontent.com/5445357/53239661-221d8180-36cf-11e9-8b1c-54c5745da717.png)

**Comment by Zohtar** [comment]
UNIcode are filtered away to try at keep the layout simple and clean.

**Comment by llybin** [comment]
1. I consider that a view in wallet must be same with explorer. If wallet allow use Unicode - need to show it correctly not "???"
2. Thai language on first screenshot. With Chinese, I think, same.

Old explorer display correctly it.

**Comment by Zoh63392187** [comment]
You are correct on the langue part and it's now fixed.
At a later point unicode like this: 
![image](https://user-images.githubusercontent.com/32987300/53720716-b91dd280-3e61-11e9-9d1e-3f943a5ddd11.png)

**Comment by llybin** [comment]
Hello. Looks like a string truncates per bytes not per symbols.

https://explorer.burstcoin.network/?action=blocks
https://explorer.burstcoin.network/?action=block_inspect&height=621725

![image](https://user-images.githubusercontent.com/5445357/57932208-989fd900-78e4-11e9-8e21-b03b7bf7aa3a.png)
