### ISSUE TITLE
Compatibility exists in PHP7. Do you allow me to submit code?

### ISSUE THREAD

**Issue by lxj-my** [burst-apps-team/burst-explorer#3]
Compatibility exists in PHP7. Do you allow me to submit code?
for example,in cron_.php

![image](https://user-images.githubusercontent.com/20417530/66464433-8f8cef80-eab1-11e9-856c-9d411ba0c79e.png)
![image](https://user-images.githubusercontent.com/20417530/66464480-acc1be00-eab1-11e9-90b3-64881a751f27.png)
![image](https://user-images.githubusercontent.com/20417530/66464495-b4816280-eab1-11e9-9217-4b3359ecd185.png)
![image](https://user-images.githubusercontent.com/20417530/66464512-bd723400-eab1-11e9-8bf6-83318194fca6.png)
![image](https://user-images.githubusercontent.com/20417530/66464536-c6fb9c00-eab1-11e9-8b1a-c61e35e6b644.png)

and so on!

**Comment by harry1453** [comment]
Yes - I presume you are the one that emailed me. If you want to submit a contribution please fork the repository and open a pull request.

**Comment by lxj-my** [comment]
Hello, friend, I have submitted the timer modification scheme for burst-explorer, please help to review .thank you!
the project address: https://github.com/burst-apps-team/burst-explorer






At 2019-10-10 18:42:52, "Harry" <notifications@github.com> wrote:


Yes - I presume you are the one that emailed me. If you want to submit a contribution please fork the repository and open a pull request.

**Comment by Zoh63392187** [comment]
Input not valid
