### ISSUE TITLE
No price in mouseover

### ISSUE THREAD

**Issue by amnesia106** [burst-apps-team/burst-explorer#6]
i think cmc has changed there api. 
![cmc](https://user-images.githubusercontent.com/40226796/76511172-107e5780-6453-11ea-8ace-7e746a78763e.png)

i the balance and block overview, the auto expand of converted price show "0"

**Comment by harry1453** [comment]
@Zoh63392187 IIRC the CMC v1 API was due to shutdown sometime? Are we using that?

**Comment by harry1453** [comment]
Yup, this is due to CMC removing their v1 API:

https://pro.coinmarketcap.com/migrate

Their new plan is paid :/

**Comment by Zoh63392187** [comment]
I will look into a solution.

**Comment by Zoh63392187** [comment]
Fix
