### ISSUE TITLE
Node is not recognized since the change to v3.1.1

### ISSUE THREAD

**Issue by McCalm** [burst-apps-team/burst-explorer#7]
Since the switch to node v3.1.1, the node is no longer recognized by the signum explorer:

![grafik](https://user-images.githubusercontent.com/78034375/125071635-d8743c80-e0b9-11eb-8f98-a6556f740d71.png)

The changeover took place on 07/03/21

Port 8123 is open, peer connections > 20 v3.1.1.

**Comment by Zoh63392187** [comment]
Support is on Discord
